#ifndef DEFINITIONS_H_
#define DEFINITIONS_H_

#define R 5 // r for rounds
#define BUTTON_TOPLEFT D6
#define BUTTON_TOPRIGHT D4
#define BUTTON_BOTTOMLEFT D5
#define BUTTON_BOTTOMRIGHT D3
#define BUTTON_SNOOZE D2

#define LAST_PRESSED_LENGTH 10

#endif